name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: xcodebuild build -project calc.xcodeproj -scheme CalcTest CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Test
        run: xcodebuild test -project calc.xcodeproj -scheme CalcTest CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
